import { Integration } from './types';

export const INDUSTRIES = [
  'E-commerce (B2C)',
  'E-commerce (B2B)',
  'SaaS',
  'Agencja Marketingowa',
  'Retail (Omnichannel)',
  'Logistyka',
  'Inne',
];

export const INTEGRATIONS: Integration[] = [
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'store',
    descriptionPL: 'Sklep na WordPress. Pobieramy zamowienia, produkty i klientow.',
    descriptionEN: 'WordPress store. We sync orders, products, and customers.',
    icon: 'WO',
    available: true,
    type: 'apikey',
    fields: ['Adres sklepu (URL)', 'Klucz klienta (Consumer Key)', 'Sekret klienta (Consumer Secret)'],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'store',
    descriptionPL: 'Platforma ecommerce. Synchronizacja zamowien i magazynu.',
    descriptionEN: 'E-commerce platform. Syncs orders and inventory levels.',
    icon: 'SH',
    available: true,
    type: 'apikey',
    fields: ['Adres sklepu (URL)', 'Token Admin API'],
  },
  {
    id: 'google_ads',
    name: 'Google Ads',
    category: 'ads',
    descriptionPL: 'Kampanie reklamowe w wyszukiwarce i na YouTube.',
    descriptionEN: 'Search and YouTube campaigns.',
    icon: 'GA',
    available: true,
    type: 'oauth',
  },
  {
    id: 'meta_ads',
    name: 'Meta Ads',
    category: 'ads',
    descriptionPL: 'Reklamy na Facebooku i Instagramie.',
    descriptionEN: 'Facebook and Instagram ads.',
    icon: 'ME',
    available: true,
    type: 'oauth',
  },
  {
    id: 'tiktok_ads',
    name: 'TikTok Ads',
    category: 'ads',
    descriptionPL: 'Kampanie wideo na TikToku.',
    descriptionEN: 'Video campaigns on TikTok.',
    icon: 'TT',
    available: true,
    type: 'oauth',
  },
  {
    id: 'ga4',
    name: 'Google Analytics 4',
    category: 'analytics',
    descriptionPL: 'Analityka ruchu i konwersji.',
    descriptionEN: 'Traffic and conversion analytics.',
    icon: 'G4',
    available: true,
    type: 'oauth',
  },
];

export const TERMINAL_LOGS = [
  '> Inicjalizacja srodowiska klienta: {company_id}...',
  '> Alokacja zasobow Google Cloud (region: europe-central2)... [OK]',
  '> Tworzenie datasetow BigQuery: {company_id}_raw, {company_id}_curated... [OK]',
  '> Provisioning dedykowanych kont serwisowych... [OK]',
  '> Konfiguracja skarbca Secret Manager dla kluczy API... [OK]',
  '> Uruchamianie potokow ETL dla wybranych zrodel: {sources}...',
  '> Weryfikacja warstwy szyfrowania: AES-256 wlaczone... [OK]',
  '> Wdrazanie domyslnych dashboardow i blueprintow Raportow Live... [OK]',
  '> Test gotowosci systemu... [ZALICZONY]',
  '> Przekierowanie do Obszaru Roboczego...',
];
