const DEMO_RESPONSES: Array<{ test: RegExp; text: string }> = [
  {
    test: /anomal|drop|spike|alert|issue|problem/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują krótkoterminowy spadek ROAS na Meta przy stabilnym wydatku.',
      '- Spadła konwersja na mobile, desktop pozostaje bez zmian.',
      '',
      'RYZYKO/SZANSA',
      '- Spadek jest prawdopodobnie ograniczony do jednego kanału lub segmentu.',
      '- Jest szansa na przesunięcie budżetu do lepszych kampanii.',
      '',
      'PLAN DZIAŁANIA',
      '1) Wstrzymaj na 24h zestawy o najniższym ROAS i monitoruj.',
      '2) Sprawdź ostatnie zmiany kreacji i cofnij, jeśli to potrzebne.',
      '3) Przenieś 10-15% budżetu do dwóch najlepszych kampanii.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows a short-term ROAS drop on Meta with stable spend.',
      '- Conversion rate is down on mobile while desktop remains flat.',
      '',
      'RISK/OPPORTUNITY',
      '- The drop is likely isolated to one channel or audience segment.',
      '- There is an opportunity to shift budget to higher-performing campaigns.',
      '',
      'ACTION PLAN',
      '1) Pause the lowest-ROAS ad sets for 24h and monitor recovery.',
      '2) Check recent creative changes and revert if needed.',
      '3) Reallocate 10-15% of spend to the top two campaigns.',
    ].join('\n'),
  },
  {
    test: /roas|cvr|cpa|ads|meta|google|tiktok|campaign/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują wahania ROAS między kanałami płatnymi.',
      '- CPA rośnie w jednej grupie kampanii, a CVR jest płaski.',
      '',
      'RYZYKO/SZANSA',
      '- Budżet może być kierowany do ruchu niższej jakości.',
      '- Można poprawić efektywność przez lepsze targetowanie.',
      '',
      'PLAN DZIAŁANIA',
      '1) Obniż wydatki na 20% kampanii o najniższym ROAS.',
      '2) Odśwież kreacje z najwyższym CTR z ostatnich 7 dni.',
      '3) Ustaw limit CPA i automatycznie pauzuj przekroczenia.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows ROAS volatility across paid channels.',
      '- CPA is rising on one campaign group while CVR is flat.',
      '',
      'RISK/OPPORTUNITY',
      '- Budget is likely misallocated to lower-quality traffic.',
      '- There is an opportunity to tighten targeting and recover efficiency.',
      '',
      'ACTION PLAN',
      '1) Reduce spend on the bottom 20% ROAS campaigns.',
      '2) Refresh creatives with the highest CTR in the last 7 days.',
      '3) Add a CPA ceiling and auto-pause breaches.',
    ].join('\n'),
  },
  {
    test: /inventory|stock|sku|out[- ]?of[- ]?stock|warehouse/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują ryzyko braku towaru dla topowego SKU.',
      '- Lead time wzrósł, popyt pozostaje stabilny.',
      '',
      'RYZYKO/SZANSA',
      '- Braki zmniejszą przychód i efektywność reklam.',
      '- Wcześniejsze uzupełnienie zapasów ograniczy spadki.',
      '',
      'PLAN DZIAŁANIA',
      '1) Priorytetyzuj uzupełnienie top 5 SKU wg marży.',
      '2) Tymczasowo przenieś budżet na SKU dostępne od ręki.',
      '3) Dodaj alert niskiego stanu przy 7 dniach pokrycia.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows a stock-out risk on a top-selling SKU.',
      '- Lead time increased while demand stayed stable.',
      '',
      'RISK/OPPORTUNITY',
      '- Stock-outs will reduce revenue and ad efficiency.',
      '- Pre-emptive restock can prevent a multi-week dip.',
      '',
      'ACTION PLAN',
      '1) Prioritize replenishment for top 5 SKUs by margin.',
      '2) Temporarily shift spend to in-stock SKUs.',
      '3) Add a low-stock alert at 7 days coverage.',
    ].join('\n'),
  },
  {
    test: /return|refund|chargeback|fraud/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo wskazują podwyższone zwroty na produktach w promocji.',
      '- Zwroty koncentrują się w jednej kategorii.',
      '',
      'RYZYKO/SZANSA',
      '- Zwroty obniżają marżę i mogą maskować realny ROAS.',
      '- Bardziej selektywne promocje poprawią zysk netto.',
      '',
      'PLAN DZIAŁANIA',
      '1) Zmniejsz rabaty na SKU o najwyższych zwrotach.',
      '2) Sprawdź karty produktu pod kątem oczekiwań klientów.',
      '3) Mierz ROAS netto po zwrotach.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data indicates elevated return rates on discounted items.',
      '- Refunds are concentrated in one product category.',
      '',
      'RISK/OPPORTUNITY',
      '- Margin erosion from returns can hide true ROAS.',
      '- A stricter promo strategy can improve net profitability.',
      '',
      'ACTION PLAN',
      '1) Reduce discounts on high-return SKUs.',
      '2) Review product detail pages for fit/expectation gaps.',
      '3) Track net ROAS after returns.',
    ].join('\n'),
  },
  {
    test: /latency|freshness|data quality|coverage|ga4|tracking/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują opóźnioną ingestę zdarzeń i częściowe pokrycie.',
      '- Okna atrybucji są niespójne między źródłami.',
      '',
      'RYZYKO/SZANSA',
      '- Decyzje oparte o nieświeże dane mogą psuć alokację budżetu.',
      '- Poprawa świeżości danych zwiększy zaufanie do wniosków.',
      '',
      'PLAN DZIAŁANIA',
      '1) Zmierz opóźnienia pipeline per źródło i ustaw SLA.',
      '2) Zweryfikuj liczbę zdarzeń względem źródeł prawdy.',
      '3) Oznacz okresy niskiego pokrycia w raportach.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows delayed event ingestion and partial coverage.',
      '- Attribution windows appear inconsistent across sources.',
      '',
      'RISK/OPPORTUNITY',
      '- Decisions based on stale data can misallocate budget.',
      '- Fixing data freshness improves confidence in insights.',
      '',
      'ACTION PLAN',
      '1) Audit pipeline latency per source and set SLA thresholds.',
      '2) Validate event counts against source-of-truth dashboards.',
      '3) Flag low-coverage periods in reporting.',
    ].join('\n'),
  },
  {
    test: /growth|scale|ltv|vip|segment|retention/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują wzrost LTV w topowym segmencie.',
      '- Wzrasta odsetek powrotów, CAC pozostaje płaski.',
      '',
      'RYZYKO/SZANSA',
      '- Jest przestrzeń do skalowania przy utrzymaniu ROAS.',
      '- Upsell jest niedowykorzystany w segmentach wysokiego LTV.',
      '',
      'PLAN DZIAŁANIA',
      '1) Zbuduj lookalike VIP i dodaj +15% budżetu.',
      '2) Włącz cross-sell po zakupie dla top SKU.',
      '3) Ustaw guardrail CAC i monitoruj tygodniowo.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows increasing LTV in the top customer segment.',
      '- Repeat purchase rate is rising, but CAC is flat.',
      '',
      'RISK/OPPORTUNITY',
      '- There is room to scale spend while maintaining ROAS.',
      '- Upsell opportunities are underutilized in high-LTV segments.',
      '',
      'ACTION PLAN',
      '1) Create a VIP lookalike and allocate +15% budget.',
      '2) Launch post-purchase cross-sell flows for top SKUs.',
      '3) Set a CAC guardrail and monitor weekly.',
    ].join('\n'),
  },
  {
    test: /margin|profit|p&l|pandl|cost|shipping/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo wskazują presję marżową przez dostawę i rabaty.',
      '- AOV stabilne, ale zysk netto per zamówienie spada.',
      '',
      'RYZYKO/SZANSA',
      '- Koszty dostawy mogą niwelować zyski ze skali.',
      '- Odbudowa marży jest możliwa przez rabaty warstwowe.',
      '',
      'PLAN DZIAŁANIA',
      '1) Wprowadź próg darmowej dostawy + bundling.',
      '2) Ogranicz rabaty na niskomarżowe SKU.',
      '3) Monitoruj marżę netto per kanał co tydzień.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data indicates margin pressure from shipping and discounts.',
      '- AOV is stable, but net profit per order is trending down.',
      '',
      'RISK/OPPORTUNITY',
      '- Shipping costs can erase gains from higher volume.',
      '- Margin recovery is possible through tiered discounting.',
      '',
      'ACTION PLAN',
      '1) Introduce free-shipping threshold + bundle offers.',
      '2) Reduce discounts on low-margin SKUs.',
      '3) Track net margin by channel weekly.',
    ].join('\n'),
  },
  {
    test: /pricing|discount|promo|coupon/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują silną zależność od rabatów w jednym kanale.',
      '- AOV stabilne, ale marża netto jest ściśnięta.',
      '',
      'RYZYKO/SZANSA',
      '- Nadmierne rabaty uczą klientów czekać na promocje.',
      '- Lepsze progi cenowe mogą podnieść marżę bez spadku wolumenu.',
      '',
      'PLAN DZIAŁANIA',
      '1) Wprowadź rabaty warstwowe powiązane z progami AOV.',
      '2) Ogranicz kupony do nowych klientów lub niskiego LTV.',
      '3) Monitoruj marżę netto per typ promocji co tydzień.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows heavy discount dependency in one channel.',
      '- AOV is stable, but net margin is compressed.',
      '',
      'RISK/OPPORTUNITY',
      '- Over-discounting can train customers to wait for promos.',
      '- Better price tiers can lift margin without losing volume.',
      '',
      'ACTION PLAN',
      '1) Introduce tiered discounts tied to AOV thresholds.',
      '2) Limit coupons to first-time buyers or low-LTV segments.',
      '3) Track net margin by promotion type weekly.',
    ].join('\n'),
  },
  {
    test: /cohort|retention|repeat|churn/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo pokazują słabszy repeat rate po 30 dniach.',
      '- Kohorty o wysokim LTV skupiają się w jednym kanale.',
      '',
      'RYZYKO/SZANSA',
      '- Odpływ po pierwszym zakupie ogranicza wzrost LTV.',
      '- Retencja per kohorta może podnieść rentowność.',
      '',
      'PLAN DZIAŁANIA',
      '1) Dodaj win-back po 30 dniach z ofertami per produkt.',
      '2) Segmentuj kampanie retencyjne wg kanału pozyskania.',
      '3) Monitoruj LTV vs CAC per kohorta miesięcznie.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data shows weaker repeat rate after day 30.',
      '- High-LTV cohorts are concentrated in a single channel.',
      '',
      'RISK/OPPORTUNITY',
      '- Churn after the first purchase caps LTV growth.',
      '- Cohort-specific retention flows can lift profitability.',
      '',
      'ACTION PLAN',
      '1) Add a 30-day win-back flow with product-specific offers.',
      '2) Segment retention campaigns by acquisition channel.',
      '3) Track cohort LTV vs CAC monthly.',
    ].join('\n'),
  },
  {
    test: /attribution|incremental|lift|model/i,
    text: [
      'PL:',
      'OBSERWACJA',
      '- Dane demo sugerują bias atrybucji w stronę last-click.',
      '- Konwersje wspomagane są niedoszacowane.',
      '',
      'RYZYKO/SZANSA',
      '- Budżet może być zbyt mocno cięty w górnym lejku.',
      '- Zbalansowany model ustabilizuje wydajność.',
      '',
      'PLAN DZIAŁANIA',
      '1) Porównuj atrybucję last-click z data-driven co tydzień.',
      '2) Uruchom mały holdout na wydatkach top-of-funnel.',
      '3) Skoryguj reguły budżetowe o przychód assisted.',
      '',
      'EN:',
      'OBSERVATION',
      '- Demo data suggests attribution bias toward last-click channels.',
      '- Assisted conversions are underreported.',
      '',
      'RISK/OPPORTUNITY',
      '- Budget may be shifted away from upper-funnel channels unfairly.',
      '- A balanced model can stabilize performance.',
      '',
      'ACTION PLAN',
      '1) Compare last-click vs data-driven attribution weekly.',
      '2) Run a small holdout test on top-of-funnel spend.',
      '3) Adjust budget rules to account for assisted revenue.',
    ].join('\n'),
  },
];

const DEFAULT_DEMO_RESPONSE = [
  'PL:',
  'OBSERWACJA',
  '- Dane demo są dostępne, ale pytanie jest zbyt ogólne.',
  '',
  'RYZYKO/SZANSA',
  '- Bez konkretnego KPI rekomendacje będą zbyt szerokie.',
  '',
  'PLAN DZIAŁANIA',
  '1) Zapytaj o anomalie, wzrost lub P&L, aby uzyskać konkrety.',
  '2) Podaj KPI (ROAS, CVR, AOV, marża).',
  '',
  'EN:',
  'OBSERVATION',
  '- Demo data is available, but the question is too generic.',
  '',
  'RISK/OPPORTUNITY',
  '- Without a focused KPI, recommendations may be too broad.',
  '',
  'ACTION PLAN',
  '1) Ask about anomalies, growth, or P&L to get actionable output.',
  '2) Provide a KPI focus (ROAS, CVR, AOV, margin).',
].join('\n');

export const getDemoResponse = (prompt: string): string => {
  const normalized = prompt.trim();
  if (!normalized) {
    return DEFAULT_DEMO_RESPONSE;
  }

  const match = DEMO_RESPONSES.find(({ test }) => test.test(normalized));
  return match ? match.text : DEFAULT_DEMO_RESPONSE;
};
