export const paths = {
  root: '/',
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  dashboardOverview: '/dashboard/overview',
  dashboardAnalytics: '/dashboard/analytics',
  dashboardReports: '/dashboard/reports',
  dashboardCustomers: '/dashboard/customers',
  dashboardProducts: '/dashboard/products',
  dashboardIntegrations: '/dashboard/integrations',
  dashboardSupport: '/dashboard/support',
  dashboardSettings: '/dashboard/settings',
  legalTerms: '/legal/terms',
  legalPrivacy: '/legal/privacy',
  legalCookies: '/legal/cookies',
  legalDpa: '/legal/dpa',
  legalAi: '/legal/ai',
  legalAccessibility: '/legal/accessibility',
} as const;
